//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2016/11/28 星期一 23:29:59
namespace IMCSystem.Console.IMCSystem.Server.Models
{
    /// <summary>
    /// There are no comments for DrugSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("DrugSingle")]
    public partial class DrugSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Drug>
    {
        /// <summary>
        /// Initialize a new DrugSingle object.
        /// </summary>
        public DrugSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new DrugSingle object.
        /// </summary>
        public DrugSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new DrugSingle object.
        /// </summary>
        public DrugSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Drug> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Images in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Images")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::IMCSystem.Console.IMCSystem.Server.Models.DrugImage> Images
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Images == null))
                {
                    this._Images = Context.CreateQuery<global::IMCSystem.Console.IMCSystem.Server.Models.DrugImage>(GetPath("Images"));
                }
                return this._Images;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::IMCSystem.Console.IMCSystem.Server.Models.DrugImage> _Images;
    }
    /// <summary>
    /// There are no comments for Drug in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Drug")]
    public partial class Drug : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Drug object.
        /// </summary>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="code">Initial value of Code.</param>
        /// <param name="barCode">Initial value of BarCode.</param>
        /// <param name="packageNum">Initial value of PackageNum.</param>
        /// <param name="length">Initial value of Length.</param>
        /// <param name="width">Initial value of Width.</param>
        /// <param name="height">Initial value of Height.</param>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="updatedAt">Initial value of UpdatedAt.</param>
        /// <param name="createdAt">Initial value of CreatedAt.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Drug CreateDrug(string name, 
                    string code, 
                    string barCode, 
                    int packageNum, 
                    double length, 
                    double width, 
                    double height, 
                    int ID, 
                    global::System.DateTimeOffset updatedAt, 
                    global::System.DateTimeOffset createdAt)
        {
            Drug drug = new Drug();
            drug.Name = name;
            drug.Code = code;
            drug.BarCode = barCode;
            drug.PackageNum = packageNum;
            drug.Length = length;
            drug.Width = width;
            drug.Height = height;
            drug.Id = ID;
            drug.UpdatedAt = updatedAt;
            drug.CreatedAt = createdAt;
            return drug;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property AliasName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AliasName")]
        public string AliasName
        {
            get
            {
                return this._AliasName;
            }
            set
            {
                this.OnAliasNameChanging(value);
                this._AliasName = value;
                this.OnAliasNameChanged();
                this.OnPropertyChanged("AliasName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _AliasName;
        partial void OnAliasNameChanging(string value);
        partial void OnAliasNameChanged();
        /// <summary>
        /// There are no comments for Property Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Code")]
        public string Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this._Code = value;
                this.OnCodeChanged();
                this.OnPropertyChanged("Code");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Code;
        partial void OnCodeChanging(string value);
        partial void OnCodeChanged();
        /// <summary>
        /// There are no comments for Property BarCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BarCode")]
        public string BarCode
        {
            get
            {
                return this._BarCode;
            }
            set
            {
                this.OnBarCodeChanging(value);
                this._BarCode = value;
                this.OnBarCodeChanged();
                this.OnPropertyChanged("BarCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _BarCode;
        partial void OnBarCodeChanging(string value);
        partial void OnBarCodeChanged();
        /// <summary>
        /// There are no comments for Property SuperCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("SuperCode")]
        public string SuperCode
        {
            get
            {
                return this._SuperCode;
            }
            set
            {
                this.OnSuperCodeChanging(value);
                this._SuperCode = value;
                this.OnSuperCodeChanged();
                this.OnPropertyChanged("SuperCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _SuperCode;
        partial void OnSuperCodeChanging(string value);
        partial void OnSuperCodeChanged();
        /// <summary>
        /// There are no comments for Property SearchCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("SearchCode")]
        public string SearchCode
        {
            get
            {
                return this._SearchCode;
            }
            set
            {
                this.OnSearchCodeChanging(value);
                this._SearchCode = value;
                this.OnSearchCodeChanged();
                this.OnPropertyChanged("SearchCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _SearchCode;
        partial void OnSearchCodeChanging(string value);
        partial void OnSearchCodeChanged();
        /// <summary>
        /// There are no comments for Property Specification in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Specification")]
        public string Specification
        {
            get
            {
                return this._Specification;
            }
            set
            {
                this.OnSpecificationChanging(value);
                this._Specification = value;
                this.OnSpecificationChanged();
                this.OnPropertyChanged("Specification");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Specification;
        partial void OnSpecificationChanging(string value);
        partial void OnSpecificationChanged();
        /// <summary>
        /// There are no comments for Property PackageUnit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PackageUnit")]
        public string PackageUnit
        {
            get
            {
                return this._PackageUnit;
            }
            set
            {
                this.OnPackageUnitChanging(value);
                this._PackageUnit = value;
                this.OnPackageUnitChanged();
                this.OnPropertyChanged("PackageUnit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _PackageUnit;
        partial void OnPackageUnitChanging(string value);
        partial void OnPackageUnitChanged();
        /// <summary>
        /// There are no comments for Property PackageNum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PackageNum")]
        public int PackageNum
        {
            get
            {
                return this._PackageNum;
            }
            set
            {
                this.OnPackageNumChanging(value);
                this._PackageNum = value;
                this.OnPackageNumChanged();
                this.OnPropertyChanged("PackageNum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _PackageNum;
        partial void OnPackageNumChanging(int value);
        partial void OnPackageNumChanged();
        /// <summary>
        /// There are no comments for Property Vendor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Vendor")]
        public string Vendor
        {
            get
            {
                return this._Vendor;
            }
            set
            {
                this.OnVendorChanging(value);
                this._Vendor = value;
                this.OnVendorChanged();
                this.OnPropertyChanged("Vendor");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Vendor;
        partial void OnVendorChanging(string value);
        partial void OnVendorChanged();
        /// <summary>
        /// There are no comments for Property VendorCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("VendorCode")]
        public string VendorCode
        {
            get
            {
                return this._VendorCode;
            }
            set
            {
                this.OnVendorCodeChanging(value);
                this._VendorCode = value;
                this.OnVendorCodeChanged();
                this.OnPropertyChanged("VendorCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _VendorCode;
        partial void OnVendorCodeChanging(string value);
        partial void OnVendorCodeChanged();
        /// <summary>
        /// There are no comments for Property Notes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Notes")]
        public string Notes
        {
            get
            {
                return this._Notes;
            }
            set
            {
                this.OnNotesChanging(value);
                this._Notes = value;
                this.OnNotesChanged();
                this.OnPropertyChanged("Notes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Notes;
        partial void OnNotesChanging(string value);
        partial void OnNotesChanged();
        /// <summary>
        /// There are no comments for Property Length in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Length")]
        public double Length
        {
            get
            {
                return this._Length;
            }
            set
            {
                this.OnLengthChanging(value);
                this._Length = value;
                this.OnLengthChanged();
                this.OnPropertyChanged("Length");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private double _Length;
        partial void OnLengthChanging(double value);
        partial void OnLengthChanged();
        /// <summary>
        /// There are no comments for Property Width in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Width")]
        public double Width
        {
            get
            {
                return this._Width;
            }
            set
            {
                this.OnWidthChanging(value);
                this._Width = value;
                this.OnWidthChanged();
                this.OnPropertyChanged("Width");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private double _Width;
        partial void OnWidthChanging(double value);
        partial void OnWidthChanged();
        /// <summary>
        /// There are no comments for Property Height in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Height")]
        public double Height
        {
            get
            {
                return this._Height;
            }
            set
            {
                this.OnHeightChanging(value);
                this._Height = value;
                this.OnHeightChanged();
                this.OnPropertyChanged("Height");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private double _Height;
        partial void OnHeightChanging(double value);
        partial void OnHeightChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property UpdatedAt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("UpdatedAt")]
        public global::System.DateTimeOffset UpdatedAt
        {
            get
            {
                return this._UpdatedAt;
            }
            set
            {
                this.OnUpdatedAtChanging(value);
                this._UpdatedAt = value;
                this.OnUpdatedAtChanged();
                this.OnPropertyChanged("UpdatedAt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _UpdatedAt;
        partial void OnUpdatedAtChanging(global::System.DateTimeOffset value);
        partial void OnUpdatedAtChanged();
        /// <summary>
        /// There are no comments for Property CreatedAt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CreatedAt")]
        public global::System.DateTimeOffset CreatedAt
        {
            get
            {
                return this._CreatedAt;
            }
            set
            {
                this.OnCreatedAtChanging(value);
                this._CreatedAt = value;
                this.OnCreatedAtChanged();
                this.OnPropertyChanged("CreatedAt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _CreatedAt;
        partial void OnCreatedAtChanging(global::System.DateTimeOffset value);
        partial void OnCreatedAtChanged();
        /// <summary>
        /// There are no comments for Property Images in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Images")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::IMCSystem.Console.IMCSystem.Server.Models.DrugImage> Images
        {
            get
            {
                return this._Images;
            }
            set
            {
                this.OnImagesChanging(value);
                this._Images = value;
                this.OnImagesChanged();
                this.OnPropertyChanged("Images");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::IMCSystem.Console.IMCSystem.Server.Models.DrugImage> _Images = new global::Microsoft.OData.Client.DataServiceCollection<global::IMCSystem.Console.IMCSystem.Server.Models.DrugImage>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnImagesChanging(global::Microsoft.OData.Client.DataServiceCollection<global::IMCSystem.Console.IMCSystem.Server.Models.DrugImage> value);
        partial void OnImagesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DrugImageSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("DrugImageSingle")]
    public partial class DrugImageSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<DrugImage>
    {
        /// <summary>
        /// Initialize a new DrugImageSingle object.
        /// </summary>
        public DrugImageSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new DrugImageSingle object.
        /// </summary>
        public DrugImageSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new DrugImageSingle object.
        /// </summary>
        public DrugImageSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<DrugImage> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Drug in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Drug")]
        public global::IMCSystem.Console.IMCSystem.Server.Models.DrugSingle Drug
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Drug == null))
                {
                    this._Drug = new global::IMCSystem.Console.IMCSystem.Server.Models.DrugSingle(this.Context, GetPath("Drug"));
                }
                return this._Drug;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::IMCSystem.Console.IMCSystem.Server.Models.DrugSingle _Drug;
    }
    /// <summary>
    /// There are no comments for DrugImage in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("DrugImage")]
    public partial class DrugImage : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new DrugImage object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="updatedAt">Initial value of UpdatedAt.</param>
        /// <param name="createdAt">Initial value of CreatedAt.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static DrugImage CreateDrugImage(int ID, global::System.DateTimeOffset updatedAt, global::System.DateTimeOffset createdAt)
        {
            DrugImage drugImage = new DrugImage();
            drugImage.Id = ID;
            drugImage.UpdatedAt = updatedAt;
            drugImage.CreatedAt = createdAt;
            return drugImage;
        }
        /// <summary>
        /// There are no comments for Property DrugId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DrugId")]
        public global::System.Nullable<int> DrugId
        {
            get
            {
                return this._DrugId;
            }
            set
            {
                this.OnDrugIdChanging(value);
                this._DrugId = value;
                this.OnDrugIdChanged();
                this.OnPropertyChanged("DrugId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _DrugId;
        partial void OnDrugIdChanging(global::System.Nullable<int> value);
        partial void OnDrugIdChanged();
        /// <summary>
        /// There are no comments for Property Content in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Content")]
        public byte[] Content
        {
            get
            {
                return this._Content;
            }
            set
            {
                this.OnContentChanging(value);
                this._Content = value;
                this.OnContentChanged();
                this.OnPropertyChanged("Content");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private byte[] _Content;
        partial void OnContentChanging(byte[] value);
        partial void OnContentChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property UpdatedAt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("UpdatedAt")]
        public global::System.DateTimeOffset UpdatedAt
        {
            get
            {
                return this._UpdatedAt;
            }
            set
            {
                this.OnUpdatedAtChanging(value);
                this._UpdatedAt = value;
                this.OnUpdatedAtChanged();
                this.OnPropertyChanged("UpdatedAt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _UpdatedAt;
        partial void OnUpdatedAtChanging(global::System.DateTimeOffset value);
        partial void OnUpdatedAtChanged();
        /// <summary>
        /// There are no comments for Property CreatedAt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CreatedAt")]
        public global::System.DateTimeOffset CreatedAt
        {
            get
            {
                return this._CreatedAt;
            }
            set
            {
                this.OnCreatedAtChanging(value);
                this._CreatedAt = value;
                this.OnCreatedAtChanged();
                this.OnPropertyChanged("CreatedAt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _CreatedAt;
        partial void OnCreatedAtChanging(global::System.DateTimeOffset value);
        partial void OnCreatedAtChanged();
        /// <summary>
        /// There are no comments for Property Drug in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Drug")]
        public global::IMCSystem.Console.IMCSystem.Server.Models.Drug Drug
        {
            get
            {
                return this._Drug;
            }
            set
            {
                this.OnDrugChanging(value);
                this._Drug = value;
                this.OnDrugChanged();
                this.OnPropertyChanged("Drug");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::IMCSystem.Console.IMCSystem.Server.Models.Drug _Drug;
        partial void OnDrugChanging(global::IMCSystem.Console.IMCSystem.Server.Models.Drug value);
        partial void OnDrugChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::IMCSystem.Console.IMCSystem.Server.Models.Drug as global::IMCSystem.Console.IMCSystem.Server.Models.DrugSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::IMCSystem.Console.IMCSystem.Server.Models.DrugSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::IMCSystem.Console.IMCSystem.Server.Models.Drug> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::IMCSystem.Console.IMCSystem.Server.Models.DrugSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::IMCSystem.Console.IMCSystem.Server.Models.Drug as global::IMCSystem.Console.IMCSystem.Server.Models.DrugSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::IMCSystem.Console.IMCSystem.Server.Models.DrugSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::IMCSystem.Console.IMCSystem.Server.Models.Drug> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::IMCSystem.Console.IMCSystem.Server.Models.DrugSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::IMCSystem.Console.IMCSystem.Server.Models.DrugImage as global::IMCSystem.Console.IMCSystem.Server.Models.DrugImageSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::IMCSystem.Console.IMCSystem.Server.Models.DrugImageSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::IMCSystem.Console.IMCSystem.Server.Models.DrugImage> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::IMCSystem.Console.IMCSystem.Server.Models.DrugImageSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::IMCSystem.Console.IMCSystem.Server.Models.DrugImage as global::IMCSystem.Console.IMCSystem.Server.Models.DrugImageSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::IMCSystem.Console.IMCSystem.Server.Models.DrugImageSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::IMCSystem.Console.IMCSystem.Server.Models.DrugImage> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::IMCSystem.Console.IMCSystem.Server.Models.DrugImageSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace IMCSystem.Console.Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "IMCSystem.Server.Models", "IMCSystem.Console.IMCSystem.Server.Models");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "IMCSystem.Console.Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("IMCSystem.Console.IMCSystem.Server.Models", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("IMCSystem.Server.Models.", originalNameAttribute.OriginalName);
                }
                return string.Concat("IMCSystem.Server.Models.", clientType.Name);
            }
            if (clientType.Namespace.Equals("IMCSystem.Console.Default", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Default.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Default.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Drug in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Drug")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::IMCSystem.Console.IMCSystem.Server.Models.Drug> Drug
        {
            get
            {
                if ((this._Drug == null))
                {
                    this._Drug = base.CreateQuery<global::IMCSystem.Console.IMCSystem.Server.Models.Drug>("Drug");
                }
                return this._Drug;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::IMCSystem.Console.IMCSystem.Server.Models.Drug> _Drug;
        /// <summary>
        /// There are no comments for Drug in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToDrug(global::IMCSystem.Console.IMCSystem.Server.Models.Drug drug)
        {
            base.AddObject("Drug", drug);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""IMCSystem.Server.Models"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Drug"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Name"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""AliasName"" Type=""Edm.String"" />
        <Property Name=""Code"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""BarCode"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""SuperCode"" Type=""Edm.String"" />
        <Property Name=""SearchCode"" Type=""Edm.String"" />
        <Property Name=""Specification"" Type=""Edm.String"" />
        <Property Name=""PackageUnit"" Type=""Edm.String"" />
        <Property Name=""PackageNum"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Vendor"" Type=""Edm.String"" />
        <Property Name=""VendorCode"" Type=""Edm.String"" />
        <Property Name=""Notes"" Type=""Edm.String"" />
        <Property Name=""Length"" Type=""Edm.Double"" Nullable=""false"" />
        <Property Name=""Width"" Type=""Edm.Double"" Nullable=""false"" />
        <Property Name=""Height"" Type=""Edm.Double"" Nullable=""false"" />
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""UpdatedAt"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""CreatedAt"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <NavigationProperty Name=""Images"" Type=""Collection(IMCSystem.Server.Models.DrugImage)"" />
      </EntityType>
      <EntityType Name=""DrugImage"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""DrugId"" Type=""Edm.Int32"" />
        <Property Name=""Content"" Type=""Edm.Binary"" />
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""UpdatedAt"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""CreatedAt"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <NavigationProperty Name=""Drug"" Type=""IMCSystem.Server.Models.Drug"">
          <ReferentialConstraint Property=""DrugId"" ReferencedProperty=""Id"" />
        </NavigationProperty>
      </EntityType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""Container"">
        <EntitySet Name=""Drug"" EntityType=""IMCSystem.Server.Models.Drug"">
          <Annotation Term=""Org.OData.Core.V1.OptimisticConcurrency"">
            <Collection>
              <PropertyPath>UpdatedAt</PropertyPath>
            </Collection>
          </Annotation>
        </EntitySet>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
